In [3]:
import numpy as np
list = list(range(1,10))
arr = np.array(list)


In [8]:
lst = arr[[1,2,3]]
print(lst)

[2 3 4]


In [16]:
arr2=np.array([[1,3,4]
               ,[1,2,3],
               [21,2,4],
               [1,2,5]])
print(arr2)

[[ 1  3  4]
 [ 1  2  3]
 [21  2  4]
 [ 1  2  5]]


In [ ]:
#arr[[rows],[columns]]
print(arr2[[1,2],[1,1]])

[2 2]
[ 3 21]


In [19]:
print(arr2[arr2>2])

[ 3  4  3 21  4  5]


In [20]:
#iteration in array
for i in np.nditer(arr2):
    print(i)

1
3
4
1
2
3
21
2
4
1
2
5
