In [2]:
import numpy as np

In [3]:
# 1d array
arr1 = list(range(1,10))
arr1= np.array(arr1)
print(arr1.ndim)

# 2d Array
arr2=np.array([[1,3,4]
               ,[1,2,3],
               [21,2,4],
               [1,2,5]])
print(arr2.ndim)

# 3d array
arr3 = np.array([
    #1st floor
    [[1,2,3,5],
    [2,5,6,2]],

    #2nd floor
    [[1,2,34,5],
    [2,5,67,2]],

    #3rd floor
    [[1,2,35,5],
    [2,5,65,26]]
    ])
print(arr3.ndim)

1
2
3


In [4]:
#indexing
print(arr1)
print(arr1[7])
print(arr3)
print(arr3[1][0][2])

[1 2 3 4 5 6 7 8 9]
8
[[[ 1  2  3  5]
  [ 2  5  6  2]]

 [[ 1  2 34  5]
  [ 2  5 67  2]]

 [[ 1  2 35  5]
  [ 2  5 65 26]]]
34


In [5]:
print(arr1)

[1 2 3 4 5 6 7 8 9]


In [6]:
#slicing for 1d array = arr[start:end:step]
arr1_mod = arr1[1:5]
print(arr1_mod)

[2 3 4 5]


In [7]:
print(arr2)

[[ 1  3  4]
 [ 1  2  3]
 [21  2  4]
 [ 1  2  5]]


In [8]:
#slicing for 2d array = arr[row_start:row_end:row_step, col_start:col_end:col_step]
arr2_mod = arr2[0:3:2,0:2:1]
print(arr2_mod.ndim)


2


In [9]:
arr3

array([[[ 1,  2,  3,  5],
        [ 2,  5,  6,  2]],

       [[ 1,  2, 34,  5],
        [ 2,  5, 67,  2]],

       [[ 1,  2, 35,  5],
        [ 2,  5, 65, 26]]])

In [10]:
# slicing for 3d array = arr3[floor start: end:step, row start:end:step, col start:end:step]

arr3_mod = arr3[0:3:2,0:1]
arr3_mod

array([[[ 1,  2,  3,  5]],

       [[ 1,  2, 35,  5]]])