In [1]:
import numpy as np

### Diagonal matrix

In [5]:
arr = np.diag([1,2,3,4,6])
print(arr)
print(arr.shape)
print(arr.dtype)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 6]]
(5, 5)
int64


### identity matrix

In [ ]:
#np.eye(row,columns,k) 
arr = np.eye(10,5,1)
print(arr)

arr = np.eye(5,6,2)
print(arr)

[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]]
