In [1]:
import numpy as np

### List

In [2]:
lst = [10,20,30,40,5]
arr = np.array(lst,dtype = np.int32)
print(type(arr))
print(arr)
print(arr.dtype)


<class 'numpy.ndarray'>
[10 20 30 40  5]
int32


In [ ]:
mix_list = [10,20,'hello',23.4,True]
arr= np.array(mix_list)
print(arr)
print(type(arr))
print(arr.dtype)

['10' '20' 'hello' '23.4' 'True']
<class 'numpy.ndarray'>
<U32


In [ ]:
matrix = [
    [[1,2,34,5],
    [2,50,60,2]],

    #2nd floor
    [[1,2,34,5],
    [2,50,60,2]],

    #3rd floor
    [[1,2,34,5],
    [2,50,60,2]]
]

arr = np.array(matrix)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[[[ 1  2 34  5]
  [ 2 50 60  2]]

 [[ 1  2 34  5]
  [ 2 50 60  2]]

 [[ 1  2 34  5]
  [ 2 50 60  2]]]
<class 'numpy.ndarray'>
int64
(3, 2, 4)
3


#### tuple

In [ ]:
tpl = (1,3,3,4)
arr = np.array(tpl)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[1 3 3 4]
<class 'numpy.ndarray'>
int64
(4,)
1


#### Set

In [ ]:
set = {1,2,3}
arr = np.array(list(set))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[1 2 3]
<class 'numpy.ndarray'>
int64
(3,)
1


#### Dict

In [ ]:
dic = {
    'a':[1,2,3],
    'b' :[2,34,5],
    'c': [55,4,6],
    'd':[4,3,5]
}
keys = dic.keys()
values = dic.values()
item = dic.items()

#keys to ndarray
arr = np.array(list(keys))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)


['a' 'b' 'c' 'd']
<class 'numpy.ndarray'>
<U1
(4,)
1


In [ ]:
#values to ndarray
arr = np.array(list(values))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[[ 1  2  3]
 [ 2 34  5]
 [55  4  6]
 [ 4  3  5]]
<class 'numpy.ndarray'>
int64
(4, 3)
2


In [ ]:
# items to ndarray\arr = np.array(list(values))
arr = np.array(list(item))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.ndim)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (4, 2) + inhomogeneous part.