In [2]:
import numpy as np


In [9]:
#np.arange(start,end, step)
arr = np.arange(1,10,1).reshape(3,3)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
int64
(3, 3)
2


In [14]:
#np.linespace(start,end, how_much_point_to_pick)
arr = np.linspace(1,10,12)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[ 1.          1.81818182  2.63636364  3.45454545  4.27272727  5.09090909
  5.90909091  6.72727273  7.54545455  8.36363636  9.18181818 10.        ]
<class 'numpy.ndarray'>
float64
(12,)
1


In [3]:
#np.logspace(start,end(included), how_much_point_to_pick)
arr = np.logspace(1,4,12)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[   10.            18.73817423    35.11191734    65.79332247
   123.28467394   231.01297001   432.87612811   811.13083079
  1519.91108295  2848.03586844  5336.69923121 10000.        ]
<class 'numpy.ndarray'>
float64
(12,)
1
