In [1]:
import numpy as np

In [15]:
#np.zeros
arr = np.zeros((3,1,3))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[[[0. 0. 0.]]

 [[0. 0. 0.]]

 [[0. 0. 0.]]]
<class 'numpy.ndarray'>
float64
(3, 1, 3)
3


In [16]:
arr3 = np.array([
    #1st floor
    [[1,2,34,5],
    [2,50,60,2]],

    #2nd floor
    [[1,2,34,5],
    [2,50,60,2]],
    ])

In [17]:
#np.zeros_like
arr = np.zeros_like(arr3)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[[[0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]]]
<class 'numpy.ndarray'>
int64
(2, 2, 4)
3


In [24]:
# np.like
arr = np.ones((1,2,3))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[[[1. 1. 1.]
  [1. 1. 1.]]]
<class 'numpy.ndarray'>
float64
(1, 2, 3)
3


In [ ]:
# np.like
arr = np.ones_like(arr3)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[[[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]]
<class 'numpy.ndarray'>
int64
(2, 2, 4)
3


In [ ]:
#np.empty
arr = np.empty((4,2,2),dtype = np.int32)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]

 [[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]
<class 'numpy.ndarray'>
int32
(4, 2, 2)
3


In [49]:
#np.full

arr = np.full((4,3),10)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[[10 10 10]
 [10 10 10]
 [10 10 10]
 [10 10 10]]
<class 'numpy.ndarray'>
int64
(4, 3)
2


In [50]:
arr = np.full((4,3),np.inf)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[[inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]]
<class 'numpy.ndarray'>
float64
(4, 3)
2


In [6]:
arr = np.array([[10,20,30],[40,50,60]])
arr[:,1]


array([20, 50])