In [1]:
import numpy as np

In [ ]:
arr = np.random.rand(2,3) # 0 -> 1 obdi value generate kore sobdik a soman kore
print(arr)
print(type(arr))
print(arr.dtype)

[[0.05657975 0.63437647 0.35393371]
 [0.32935032 0.80350257 0.47007186]]
<class 'numpy.ndarray'>
float64


In [ ]:
#np.random.randint(starting,end, shape)
arr = np.random.randint(0,100, (2,3))
print(arr)
print(arr.shape)
print(arr.dtype)

[[24 84  6]
 [80 32 71]]
(2, 3)
int32


In [13]:
#np.random.uniform(starting,end, shape)
arr = np.random.uniform(50,100, (4,3,3))
print(arr)
print(arr.shape)
print(arr.dtype)

[[[60.79091862 63.67139397 88.97164436]
  [51.66630389 95.01878563 91.34417314]
  [93.80845453 98.15367414 55.90226427]]

 [[76.15107439 64.31968389 67.1773251 ]
  [61.14635744 62.02565586 80.45444944]
  [86.30026891 77.68156833 59.55368279]]

 [[60.13464966 98.16641137 88.28515554]
  [93.45396375 70.32162705 85.98409395]
  [99.49983604 99.43057109 73.25795855]]

 [[72.08372913 70.21185041 75.48087007]
  [61.17364923 91.33251489 74.21731993]
  [60.22313307 72.07666111 86.3253253 ]]]
(4, 3, 3)
float64
