In [ ]:
# need to explore mathmetical function of numpy
import numpy as np

In [7]:
a = np.array(range(1,10))
b = np.array(range(2,11))
print(a)
print(b)

[1 2 3 4 5 6 7 8 9]
[ 2  3  4  5  6  7  8  9 10]


In [10]:
add = a+b
print(add)

sub = a-b
print(sub)

mul = a*b
print(mul)

div = a/b
print(div)

remainder = a%b
print(remainder)

[ 3  5  7  9 11 13 15 17 19]
[-1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 2  6 12 20 30 42 56 72 90]
[0.5        0.66666667 0.75       0.8        0.83333333 0.85714286
 0.875      0.88888889 0.9       ]
[1 2 3 4 5 6 7 8 9]


#### Mathmetical function in numpy

#### Trigonmetry

In [16]:
sin_val = np.sin(a)
print(sin_val)

cos_val = np.cos(a)
print(cos_val)

#radian to degree
deg_con = np.rad2deg(a)
print(deg_con)

#deg to radian
red_con = np.deg2rad(deg_con)
print(red_con)

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026]
[ 57.29577951 114.59155903 171.88733854 229.18311805 286.47889757
 343.77467708 401.07045659 458.3662361  515.66201562]
[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [19]:
#log
base_10_log_val = np.log10(a)  # kono number ke 10 diye kotobar vhag kora jabe seta log10 er result
print(base_10_log_val)

two_diye_vhag = np.log2(a)    # kono number ke 2 diye kotobar vhag kora jabe seta
print(two_diye_vhag)

[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]
[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


In [ ]:
# squreroot
x = np.array([4,2,6,16,25])
sqrt = np.sqrt(x)
print(sqrt)

[2.         1.41421356 2.44948974 4.         5.        ]


In [24]:
# different 
sum = np.sum(x)
print(sum)

cumalative_sum = np.cumulative_sum(x)
print(cumalative_sum)

53
[ 4  6 12 28 53]
