In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,100, size=(5,10))

In [3]:
arr.shape
print(arr.ndim)
arr

2


array([[43, 98, 23, 22, 28, 35, 60, 74, 46, 61],
       [37, 24, 34, 33, 76, 86, 47, 36,  2, 89],
       [52, 46, 39, 68, 53, 42, 30, 56, 84, 29],
       [79, 12, 94, 91, 96, 60, 54,  9, 18, 18],
       [98, 45, 35, 34, 75, 84,  3, 98, 69, 40]], dtype=int32)

In [4]:
arr.reshape(10,5)
print(arr.ndim)

2


In [5]:
#row_wise flatting
flat = arr.flatten()
print(flat)
print(arr.ndim)

[43 98 23 22 28 35 60 74 46 61 37 24 34 33 76 86 47 36  2 89 52 46 39 68
 53 42 30 56 84 29 79 12 94 91 96 60 54  9 18 18 98 45 35 34 75 84  3 98
 69 40]
2


In [6]:
arr

array([[43, 98, 23, 22, 28, 35, 60, 74, 46, 61],
       [37, 24, 34, 33, 76, 86, 47, 36,  2, 89],
       [52, 46, 39, 68, 53, 42, 30, 56, 84, 29],
       [79, 12, 94, 91, 96, 60, 54,  9, 18, 18],
       [98, 45, 35, 34, 75, 84,  3, 98, 69, 40]], dtype=int32)

In [7]:
#col_wise_flatting
col_wise_flattening = np.ravel(arr,order = 'F')
print(col_wise_flattening)

[43 37 52 79 98 98 24 46 12 45 23 34 39 94 35 22 33 68 91 34 28 76 53 96
 75 35 86 42 60 84 60 47 30 54  3 74 36 56  9 98 46  2 84 18 69 61 89 29
 18 40]


In [34]:
a = np.random.randint(1,10,size=(2,3))
b = np.random.randint(20,30,size = (2,3))
print(a)
print(b)

[[8 5 7]
 [5 7 6]]
[[25 26 26]
 [20 25 27]]


In [ ]:
#concatenate
con_row = np.concatenate((a,b),axis = 0) #row_wise
print(con_row)

con_col = np.concatenate((a,b),axis =1) #col_wise 
print(con_col)

[[ 2  5  1]
 [ 4  5  6]
 [24 24 27]
 [28 21 22]]
[[ 2  5  1 24 24 27]
 [ 4  5  6 28 21 22]]


### Error during concatenate
row wise concate korar somoy col same thakbe, 
col wise concate korar somoy row same thakbe 

In [29]:
# col error 
x = np.random.randint(1,10,size=(2,3))
y = np.random.randint(20,30,size = (1,3))

con_row = np.concatenate((x,y),axis = 0)
print(con_row)


[[ 4  3  5]
 [ 2  2  4]
 [25 20 20]]


In [30]:
#col_error
con_col = np.concatenate((x,y), axis=1)
print(con_col)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [ ]:
x = np.random.randint(1,10,size=(3,1))
y = np.random.randint(20,30,size = (3,2))

con_col = np.concatenate((x,y), axis =1)
print(con_col)

[[ 3 29 21]
 [ 2 25 25]
 [ 4 25 29]]


In [ ]:
# row_error
col_row = np.concatenate((x,y), axis=0)
print(con_row)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 1 and the array at index 1 has size 2