In [1]:
import numpy as np

In [3]:
# np.where(condition, x,y) if conditon is ture keep x otherwise replace x with y
arr = np.array([15,22,55,60,19,20])

index = np.where(arr == 22) # returns index
print(index)

index = np.where(arr>20,arr,0) # returns arr
print(index)

(array([1]),)
[ 0 22 55 60  0  0]


In [8]:
math = np.array([
    [1,2,3,3],
    [2,4,3,5]
])


In [5]:
## for 2d array

index = np.where(math>4,math,0)
print(index)

[[0 0 0 5]
 [0 0 0 5]]


In [12]:
print(math)
maximum_value_index = np.argmax(math)
min_value_index = np.argmin(math)
print(maximum_value_index)
print(min_value_index)

[[1 2 3 3]
 [2 4 3 5]]
7
0
