In [2]:
import numpy as np

In [7]:
#inplace sort er jonno default array er value change hobe 
a = np.array([1,3,5,10,0])
print(a)
a.sort() 
print(a)

[ 1  3  5 10  0]
[ 0  1  3  5 10]


In [6]:
#copy sort er jonno default array er value change hobe na
x = np.array([3,1,10,15,12])
arr_sort = np.sort(x)
print(arr_sort)
print(x)

[ 1  3 10 12 15]
[ 3  1 10 15 12]


In [11]:
# 2d array sorting
mat =np.array(
    [[8,4,16],
    [12,11,15]]
)

hor_sort = np.sort(mat,axis =1)
print(hor_sort)

var_sort = np.sort(mat,axis = 0)
print(var_sort)

[[ 4  8 16]
 [11 12 15]]
[[ 8  4 15]
 [12 11 16]]
