In [1]:
import numpy as np

In [4]:
study_hours = np.array([1,2,3,4,5,6,7,8])
marks = np.array([45,55,60,70,75,80,90,92])
data = np.array([study_hours,marks])
correlation = np.corrcoef(data)
print('Correlation Matrix: \n',correlation)

Correlation Matrix: 
 [[1.         0.99339142]
 [0.99339142 1.        ]]


In [ ]:
A = np.array(
    [
        [1,2,3,5],
        [2,5,6,8]
    ]
)

B = np.array([
    [5,8,3,8],
    [9,5,6,7],
    [5,8,9,10],
    [1,2,5,4]
])

# A er columns and B er row same length er hote hobe
dot_product = np.dot(A,B)
trace = np.trace(B)   # sum of diagonal elements
print(dot_product)
print(trace)

[[ 43  52  67  72]
 [ 93 105 130 143]]
23


In [15]:
# determinent
B = np.array([
    [5,8,3,8],
    [9,5,6,7],
    [5,8,9,10],
    [1,2,5,4]
])

dm_of_b = np.linalg.det(B)
print(f'Determinent of B: {dm_of_b}')

# diagonal
B = np.array([
    [5,8,3,8],
    [9,5,6,7],
    [5,8,9,10],
    [1,2,5,4]
])

dm_of_b = np.linalg.diagonal(B)
print(f'diagonal of b: {dm_of_b}')



Determinent of B: -172.0000000000001
diagonal of b: [5 5 9 4]


In [16]:
rank_of_sq = np.linalg.matrix_rank(B)
print(rank_of_sq)

4


In [17]:
a = np.array([
    [1,2,3],
    [2,4,6]
])

rank_of_sq = np.linalg.matrix_rank(a)
print(rank_of_sq)

1


In [18]:
a = np.array([1,2,3])
b = np.array ([4,5,6])
print(a+b)

[5 7 9]


In [ ]:
A = np.array([[1, 2], 
              [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(np.dot(A,B))

[[19 22]
 [43 50]]
