In [2]:
import numpy as np

In [ ]:
# 1d,2d,3d array, printing their dimensions and shape
arr1 = np.array([1,2,3])
arr2 = np.array([
    [1,2,3],
    [2,5,7]
])
arr3 = np.array([
    

    [[1,4,5],
    [1,5,6]],

    [[1,4,5],
    [1,5,6]]
])

print(arr1.shape)
print(arr1.ndim)
print(arr2.shape)
print(arr2.ndim)
print(arr3.shape)
print(arr3.ndim)

(3,)
1
(2, 3)
2
(2, 2, 3)
3


### Problem 2

In [ ]:
# matrix of zeros
zero = np.zeros((3,3))
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
one = np.ones((2,5))
print(one)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [14]:
full = np.full((3,3),7)
print(full)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


### Problem 3

In [18]:
arr = np.arange(1,50)
even_arr = arr[arr%2 ==0]
print(even_arr)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


### Problem 4

In [30]:
arr = np.random.randint(0,15,(4,4))
print(arr)
first_row = arr[0]
last_col = arr[:,3:]
sub_arr = arr[1:3,0:]

print(f'first row: {first_row}')
print(f'last col: {last_col}')
print(f"'Sub array from center:{sub_arr}'")





[[ 3 11  5 11]
 [14  9 10  0]
 [ 3 14 14 14]
 [ 4  3  6  4]]
first row: [ 3 11  5 11]
last col: [[11]
 [ 0]
 [14]
 [ 4]]
'Sub array from center:[[14  9 10  0]
 [ 3 14 14 14]]'
